### ISSUE TITLE
It doesn't work for Chinese character 

### ISSUE THREAD

**Issue by hzh8311** [thomasWeise/ustcSlides#1]
As I use \zh{一些中文字符} and \zhb{一些中文字符}，It doesn't work for me at the output PDF file.

**Comment by thomasWeise** [comment]
Oh, interesting. So far, these commands have worked without problem in my cases.

If I download the repository and change `slides.tex` as below, it works with `pdflatex` _but not_ with `xelatex` and also _not_ with `lualatex` on my machine.

```
    \documentclass[mathserif]{beamer}%
    %
    \RequirePackage{./styles/slides}%
    %
    \title[%
    \zh{一些中文字符} %
    ]{%
    \zhb{一些中文字符}%
    }%
    %
    \begin{document}%
    %
    \startPresentation{}%
    %
    \begin{frame}%
    \frametitle{Intro}%
    \begin{itemize}%
    \item \zhb{一些中文字符}
    \item \zh{一些中文字符} 
    \end{itemize}%
    \end{frame}%
    %
    \endPresentation%
    \end{document}%%
    \endinput%
    %
```

I am not sure why that is, though. For now, I can only suggest to use `pdflatex` in this situation.

The main goal of having the `\zh` and `\zhb` commands is to make the LaTeX documents compatible between the different LaTeX implementations. I think under XeLaTeX, you probably do not need these commands and can somehow be replaced with some XeLaTeX primitives (which I, right now, do not know). 

Unfortunately, I right now do not have time to look into that deeper, so it may take some time until I figure out whether and how it can be fixed.

Cheers,
  Thomas.

**Comment by hzh8311** [comment]
It does work with `pdflatex`, but doesn't work with `xelatex`.

**Comment by thomasWeise** [comment]
Dear @hzh8311: I am currently on travels. I will review and include your suggestions and commit as soon as I come back. Many thanks for your great help!

**Comment by fylimas** [comment]
Hi, guys!

I am using it on Microsoft Windodws with TexLive2016.
This package does work on my computer with compiler LaTeX/PDFLaTeX/XeLaTeX/LuaLaTeX.

Yet another way of supporting Chinese is using `\usepackage[UTF8]{ctex}`. This gives a bonus that one can simply write in the body of the tex like `English and 中文`.

Cheers,
FieldsLi

**Comment by thomasWeise** [comment]
Hi.

Sorry for the late response.

I already worked on this issue based on @hzh8311 's comments and excellent suggestions. So the current version is basically already improved - I just forgot that this issue is still open, so I will close it now.

Anyway, to answer your comment: That is quite similar to what I am currently doing, package-internally.
- If the slides are compiled with XeLaTeX or LuaLaTeX, the scripts load `ctex` and the commands `\zh`/`\zhb` basically do nothing (`\zh` does nothing (becomes `\relax`), `zhb` just puts a box around its contents).
- However, under LaTeX and PdfLaTeX, I could not get `ctex` to work, there were problems with fonts or something. Thus, if the compiler is neither XeLaTeX nor LuaLaTeX, I load `CJKutf8` and then `\zh` wraps its contents into something like `\begin{CJK}{UTF8}{gbsn}#1\end{CJK}`.

This way, we can potentially compile the slides under all LaTeX compilers. The added benefit is that in the case that you know that you are using XeLaTeX or LuaLaTeX and do not want to use another compiler, you can simply omit the commands `\zh` and `\zhb` around Chinese text. They are then simply not needed. Only in the case that you want to (also) use LaTeX or PdfLaTeX, then you need them.
